
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class VentaInformatica extends javax.swing.JFrame {

    String nombre;
    String observaciones;
    boolean boton = false;
    String objeto;
    boolean seleccionar;
    int num = 0;
    String iva = "";
    int i = 0;

    public VentaInformatica() {
        initComponents();
//    probar_conexion();
        setIconImage(new ImageIcon(getClass().getResource("/Venturi.jpg")).getImage());
        setLocationRelativeTo(null);

    }

    public void LimpiarControles() {

        TxtNombre.setText("");
        buttonGroup1.clearSelection();
        TxtObser.setText("");
        BottonGrb.setEnabled(false);
        box1.removeAllItems();
        jLbIVA.setText("Porcentaje de IVA:");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        PANEL = new javax.swing.JPanel();
        Button1 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        Button3 = new javax.swing.JRadioButton();
        Button4 = new javax.swing.JRadioButton();
        PanelPro = new javax.swing.JPanel();
        box1 = new javax.swing.JComboBox<>();
        jLbIVA = new javax.swing.JLabel();
        ButtonMas = new javax.swing.JButton();
        ButtonMenos = new javax.swing.JButton();
        TxtObser = new javax.swing.JTextField();
        ButtonCerrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BottonGrb = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaProduc = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nota de Ventas - Venturi Hnos v1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PANEL.setBackground(new java.awt.Color(255, 255, 255));
        PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Situación IVA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        PANEL.setToolTipText("Situacion IVA");

        buttonGroup1.add(Button1);
        Button1.setText("Responsable Inscripto");
        Button1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Button1.setName(""); // NOI18N
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });

        buttonGroup1.add(Button2);
        Button2.setText("Consumidor Final");
        Button2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
        });

        buttonGroup1.add(Button3);
        Button3.setText("Responsable No Inscripto");
        Button3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
        });

        buttonGroup1.add(Button4);
        Button4.setText("Exento");
        Button4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
        PANEL.setLayout(PANELLayout);
        PANELLayout.setHorizontalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button2)
                    .addComponent(Button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button3)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );
        PANELLayout.setVerticalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        PanelPro.setBackground(new java.awt.Color(255, 255, 255));
        PanelPro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        PanelPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPro.setRequestFocusEnabled(false);

        box1.setEditable(true);
        box1.setToolTipText("");
        box1.setActionCommand("");
        box1.setAutoscrolls(true);
        box1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        box1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        box1.setLightWeightPopupEnabled(false);
        box1.setMaximumSize(new java.awt.Dimension(72, 26));
        box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                box1MouseClicked(evt);
            }
        });

        jLbIVA.setForeground(new java.awt.Color(0, 204, 51));
        jLbIVA.setText("Porcentaje de IVA:");

        javax.swing.GroupLayout PanelProLayout = new javax.swing.GroupLayout(PanelPro);
        PanelPro.setLayout(PanelProLayout);
        PanelProLayout.setHorizontalGroup(
            PanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(PanelProLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProLayout.setVerticalGroup(
            PanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLbIVA.getAccessibleContext().setAccessibleName("");

        ButtonMas.setBackground(new java.awt.Color(0, 153, 255));
        ButtonMas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ButtonMas.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMas.setText("+");
        ButtonMas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMasMouseClicked(evt);
            }
        });

        ButtonMenos.setBackground(new java.awt.Color(0, 153, 255));
        ButtonMenos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ButtonMenos.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMenos.setText("-");
        ButtonMenos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMenosMouseClicked(evt);
            }
        });

        TxtObser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Observaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        TxtObser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtObserMouseClicked(evt);
            }
        });

        ButtonCerrar.setBackground(new java.awt.Color(0, 153, 255));
        ButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCerrar.setText("Cerrar");
        ButtonCerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCerrarMouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Nuevo");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        BottonGrb.setBackground(new java.awt.Color(0, 153, 255));
        BottonGrb.setForeground(new java.awt.Color(255, 255, 255));
        BottonGrb.setText("Grabar");
        BottonGrb.setToolTipText("Grabar");
        BottonGrb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BottonGrb.setEnabled(false);
        BottonGrb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BottonGrbMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Productos Seleccionados");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListaProduc.setBorder(null);
        ListaProduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListaProduc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Placa De Vídeo Gainward Nvidia Geforce Phantom Rtx 3070 8gb Gddr6 256 Bits", "Placa De Vídeo Gainward Nvidia Geforce Phantom+ Rtx 3090 24gb Gddr6x 384 Bits", "Teclado Gamer Mecánico Corsair Gaming K68 RGB Cherry Mx Red", "Monitor Gamer Bluecase Led/Tn Negro 75hz AMD Free-Sync Ajuste de inclinación 5ms HDMI/DP 2.5k 27''", "Monitor Gamer Aoc Led Agon Ag352ucg Curvo Ultra Wide Audio Integrado 120hz Nvidia G-Sync 4ms Hdmi/Dp 2.5k 35''", "Mouse Gamer Cougar Gaming 600M Orange 8.200 DPI Laser", "Mouse Gamer Corsair Gaming M65 Pro Preto 12.000 Dpi (Rgb) Óptico", "Silla Gamer Cougar", "Memoria Gamer Hyperx Beast Black DDR5 16gb Cl40 5200mhz", "Gabinete Gamer Nzxt H7 Elite Preto Vidro Temperado Mid Tower C/Janela", "Gabinete Gamer Lian Li O11 Dynamic Branco Vidro Temperado Mid Tower C/Janela", "Gabinete Gamer Lian Li O11 Dynamic Razer Edition Preto Vidro Temperado Mid", "Fonte Real Xpg Core Reactor 850w 80 Plus Gold Modular", "Fonte Real Seasonic Focus Ssr-100 1000w 80 Plus Gold Modular - SSR-1000FX", "Source Real Cougar Gaming Bxm850 850w 80 Plus Bronce Semi Modular", "Placa De Vídeo Gainward Nvidia Geforce Ghost Gd6 Rtx 3060 12gb Gddr6 192 Bits" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaProduc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaProduc.setToolTipText("");
        ListaProduc.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(ListaProduc);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(PanelPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TxtObser, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BottonGrb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)
                        .addComponent(ButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TxtObser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottonGrb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ButtonCerrarMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        LimpiarControles();
    }//GEN-LAST:event_jButton4MouseClicked


    private void BottonGrbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottonGrbMouseClicked

        nombre = TxtNombre.getText();
        observaciones = TxtObser.getText();
        boton = Button1.isSelected() == true || Button2.isSelected() == true || Button3.isSelected() == true || Button4.isSelected() == true;
        BottonGrb.isSelected();

        if ("".equals(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe introducir el nombre del cliente", "ERROR", 0);
            TxtNombre.setText("");
            TxtNombre.requestFocus();
        } else if (nombre.length() > 59) {
            javax.swing.JOptionPane.showMessageDialog(null, "El nombre del cliente no debe superar los 60 caracteres", "ERROR", 0);
            TxtNombre.setText("");
            TxtNombre.requestFocus();
        } else if (boton == false) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion en situacion IVA ", "ERROR", 0);

        } else if ("".equals(observaciones)) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe una agregar una observacion", "ERROR", 0);
            TxtObser.setText("");
            TxtObser.requestFocus();
            TxtObserMouseClicked(evt);

        } else {

            String nombreCliente = TxtNombre.getText();
            String ivaCliente = iva;
            String observacion = TxtObser.getText();

            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLCELSIUS:1433;databaseName=dbAdventuriHnos;encrypt=true;trustServerCertificate=true", "sa", "Hacha411.");

                String QryInsert2 = "SELECT id_Cliente FROM [Compras ]";
                PreparedStatement exec2 = conn.prepareCall(QryInsert2);
                ResultSet rs = exec2.executeQuery();
                while (rs.next()) {
                    if (rs == null) {
                        i = 0;
                    } else {
                        i = rs.getInt(1) + 1;
                    }

                }

                String QryInsert3 = "SELECT DISTINCT Productos FROM Productos";
                PreparedStatement exec3 = conn.prepareCall(QryInsert3);
                exec3.executeQuery();

                String QryInsert = "INSERT INTO Compras(Nombre, Situacion_IVA, Observaciones, id_Cliente)"
                        + "VALUES('" + nombreCliente + "','" + ivaCliente + "','" + observacion + "','" + i + "')";
                PreparedStatement exec = conn.prepareCall(QryInsert);
                exec.execute();

                for (int j = 0; j < box1.getMaximumRowCount(); j++) {
                    String componente = box1.getItemAt(j);
                    int cantidad = 1;
                    
                        for (int k = 0; k < box1.getMaximumRowCount(); k++) {
                            if (componente.equalsIgnoreCase(box1.getItemAt(k))) {

                                cantidad = cantidad + 1;
                            }
                        }

                        String QryInsert1 = "INSERT INTO Productos(id_Cliente, Productos, Cantidad)"
                                + "VALUES('" + i + "','" + componente + "','" + cantidad + "')";
                        PreparedStatement exec1 = conn.prepareCall(QryInsert1);
                        exec1.execute();
                    }
                
                
                //Component Null;
                JOptionPane.showMessageDialog(null, "Store agregado correctamente", "Aviso", 0);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error Critico", 0);
            }

            if (!"".equals(observaciones)) {
                LimpiarControles();
            }
        }


    }//GEN-LAST:event_BottonGrbMouseClicked


    private void ButtonMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMasMouseClicked
        seleccionar = ListaProduc.isSelectionEmpty();
        objeto = ListaProduc.getSelectedValue();

        if (seleccionar == true) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion de la lista ", "ERROR", 0);
        } else {
            box1.setPreferredSize(new Dimension(40, 20));
            box1.addItem(objeto);
            box1.setToolTipText(objeto);

        }

    }//GEN-LAST:event_ButtonMasMouseClicked


    private void box1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box1MouseClicked

        box1.setSelectedIndex(num);

    }//GEN-LAST:event_box1MouseClicked

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        iva = "Responsable Inscripto";
        jLbIVA.setText("Porcentaje de IVA: 21 %");
    }//GEN-LAST:event_Button1MouseClicked

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        jLbIVA.setText("Porcentaje de IVA: 27 %");
        iva = "Consumidor Final";
    }//GEN-LAST:event_Button2MouseClicked

    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseClicked
        jLbIVA.setText("Porcentaje de IVA: 27 %");
        iva = "Responsable No Inscripto";
    }//GEN-LAST:event_Button3MouseClicked

    private void Button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseClicked
        jLbIVA.setText("Porcentaje de IVA: 0 %");
        iva = "Exento";
    }//GEN-LAST:event_Button4MouseClicked

    private void TxtObserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtObserMouseClicked
        BottonGrb.setEnabled(true);
    }//GEN-LAST:event_TxtObserMouseClicked

    private void ButtonMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMenosMouseClicked

        box1.removeItemAt(box1.getSelectedIndex());
    }//GEN-LAST:event_ButtonMenosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaInformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaInformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaInformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaInformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentaInformatica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonGrb;
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JRadioButton Button3;
    private javax.swing.JRadioButton Button4;
    private javax.swing.JButton ButtonCerrar;
    private javax.swing.JButton ButtonMas;
    private javax.swing.JButton ButtonMenos;
    private javax.swing.JList<String> ListaProduc;
    private javax.swing.JPanel PANEL;
    private javax.swing.JPanel PanelPro;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtObser;
    private javax.swing.JComboBox<String> box1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbIVA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
